package com.seanproctor.docking.model

import kotlin.jvm.JvmInline
import kotlinx.serialization.Serializable

/**
 * Uniquely identifies a dockable across the whole application.
 *
 * This is the persistent key: layouts reference dockables by this id, and it must remain
 * stable across application runs for layout persistence to work.
 */
@JvmInline
@Serializable
public value class DockableId(public val value: String) {
    override fun toString(): String = value
}

/**
 * Identifies a docking window (the main window or a floating window).
 */
@JvmInline
@Serializable
public value class WindowId(public val value: String) {
    override fun toString(): String = value

    public companion object {
        /** The id of the application's main docking window. */
        public val MAIN: WindowId = WindowId("main")
    }
}

/**
 * Identifies a node in the dock layout tree.
 *
 * Node ids are generated by the library, persisted with layouts, and used as stable
 * Compose keys so per-node UI state (divider drag, tab-row scroll) survives restructuring.
 */
@JvmInline
@Serializable
public value class NodeId(public val value: String) {
    override fun toString(): String = value
}

/**
 * Identifies a docking anchor: a named, stable layout region that survives all of its
 * dockables being closed. See [com.seanproctor.docking.model.DockNode.Anchor].
 */
@JvmInline
@Serializable
public value class AnchorId(public val value: String) {
    override fun toString(): String = value
}
